pipeline {
    agent {
        docker {
            image 'python:2.7.16-slim'
        }
    }
    stages {
        stage('build'){
            when{
                changeset '**/vote/**'
            }
            steps{
                echo 'Build...'
                dir('vote') {
                    sh 'pip install -i requirements.txt'
                }
            }
        }
        stage('test'){
            when{
                changeset '**/vote/**'
            }
            steps{
                echo 'Running unit tests'
                dir('vote') {
                    sh 'nose tests -v'
                }
            }
        }
    }

    post {
        always {
            echo 'END'
        }
    }
}