version: "3.9"

volumes: 
    db-data:

networks:
    instavote:
        driver: bridge 
services:
    vote:
        image: mmarquezvacas/vote:master
        ports: 
            - 5000:80
        depends_on: 
            - redis
        networks: 
            - instavote
    redis:
        image: redis:alpine
        networks: 
            - instavote

    db:
        image: postgres:9.4
        restart: always
        environment: 
            POSTGRES_PASSWORD: example
        volumes: 
            - "db-data:/var/lib/postgresql/data"
        networks: 
            - instavote

    result:
        image: mmarquezvacas/result:master
        ports: 
            - 5001:4000
        depends_on: 
            - db
        networks: 
            - instavote

    worker:
        image: mmarquezvacas/worker:master
        depends_on: 
            - redis
            - db
        networks: 
            - instavote